### ISSUE TITLE
Local variable might be clobbered in exсeption.c

### ISSUE THREAD

**Issue by shugaley** [pjsip/pjproject#3229]
### Describe the bug

Hello!

Variable `rc` might be clobbered by `longjmp`. Gcc can't resolve your try-catch blocks based on `setjmp-longjmp` and report of the potential clobbered. You change `rc` between try-catch blocks and in catch blocks and gcc suppose that you can have anywhere `longjmp` to previous `setjmp`. I believe that declaration `rc` as `volatile` is the best way to win this warning.

### Steps to reproduce

Build using `gcc-11.2` with `-Werror=clobbered -O2`.

### PJSIP version

2.12.1

### Context

alpine 3.17

### Log, call stack, etc

```shell
$ gcc -c -Wall -DPJ_AUTOCONF=1 -DNDEBUG -O2 -Werror=clobbered -fomit-frame-pointer -g -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -fPIC   -DNDEBUG -O2 -Werror=clobbered -fomit-frame-pointer -g -I../include \
	-o output/pjlib-test/exception.o \
	../src/pjlib-test/exception.c 
../src/pjlib-test/exception.c: In function 'test':
../src/pjlib-test/exception.c:120:9: error: variable 'rc' might be clobbered by 'longjmp' or 'vfork' [-Werror=clobbered]
  120 |     int rc = 0;
      |         ^~
```

**Comment by sauwming** [comment]
I tried it here and it produced many more errors other than the above, and not all can be fixed by simply adding `volatile`. Using no optimization `-O0` seems to work fine though.
