### ISSUE TITLE
ssl_sock_ossl.c: Missing OpenSSL version guards for TLS_method() and SSL_CTX_set_ciphersuites() breaks build on OpenSSL < 1.1.0

### ISSUE THREAD

**Issue by phoneben** [pjsip/pjproject#4940]
### Describe the bug

In `pjlib/src/pj/ssl_sock_ossl.c`, two OpenSSL 1.1.x+ symbols are called 
unconditionally without version guards, causing a link failure when building 
against OpenSSL 1.0.x:

1. `TLS_method()` in `init_ossl_ctx()` is called with no version guard. 
   Earlier in the same file (ssl cipher enumeration block), the equivalent 
   call is correctly guarded with `OPENSSL_VERSION_NUMBER < 0x10100000L` 
   falling back to `SSLv23_server_method()`, but this second call site was 
   not given the same treatment.

2. `SSL_CTX_set_ciphersuites()` is only guarded with `#if !USING_BORINGSSL` 
   but not for OpenSSL version. This function was introduced in OpenSSL 1.1.1 
   and does not exist in OpenSSL 1.0.x.

### Steps to reproduce

1. Build pjproject (or Asterisk with bundled pjproject) against OpenSSL 1.0.2 
   (e.g. CentOS 7 system OpenSSL: openssl-1.0.2k-fips)
2. Run: make
3. Linker will fail with:
   ./libasteriskpj.so: undefined reference to `TLS_method'
   ./libasteriskpj.so: undefined reference to `SSL_CTX_set_ciphersuites'
   collect2: error: ld returned 1 exit status

### PJSIP version

2.16

### Context

- Platform: Linux (CentOS 7 x86_64)
- OS: CentOS 7
- System OpenSSL: 1.0.2k-fips (26 Jan 2017)
- File affected: pjlib/src/pj/ssl_sock_ossl.c
- Symbols missing from OpenSSL 1.0.2: TLS_method, SSL_CTX_set_ciphersuites
- Both symbols were introduced in OpenSSL 1.1.0/1.1.1 respectively

### Log, call stack, etc

```shell
./libasteriskpj.so: undefined reference to `TLS_method'
./libasteriskpj.so: undefined reference to `SSL_CTX_set_ciphersuites'
collect2: error: ld returned 1 exit status
make[1]: *** [asterisk] Error 1
make: *** [main] Error 2

nm -D /usr/lib64/libssl.so output confirms TLS_method is absent:
0000000000039750 T DTLS_method   (only DTLS variant present)

openssl version: OpenSSL 1.0.2k-fips  26 Jan 2017
```
